#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
config device-configurator smartio-configurator capsense-configurator capsense-tuner qspi-configurator config_ezpd ez-pd-configurator modlibs library-manager seglcd-configurator config_usbdev usbdev-configurator dfuh-tool bsp-assistant :
	make -C RC-Car $@

config_bt bt-configurator config_lin lin-configurator :
	$(error $@ configurator cannot be executed at the application level. Run this command from the desired project directory.)

.PHONY: config_bt bt-configurator config device-configurator smartio-configurator capsense-configurator capsense-tuner qspi-configurator config_ezpd ez-pd-configurator modlibs library-manager seglcd-configurator config_usbdev usbdev-configurator dfuh-tool config_lin lin-configurator bsp-assistant
